[theme]
base            = "dark"
backgroundColor          = "#010104"
secondaryBackgroundColor = "#06080f"
textColor                = "#e2e8f0"
primaryColor             = "#f59e0b"
font                     = "monospace"

[server]
headless = true

[browser]
gatherUsageStats = false
