[theme]
base            = "dark"
backgroundColor          = "#020209"
secondaryBackgroundColor = "#07090f"
textColor                = "#e2e8f0"
primaryColor             = "#f59e0b"
font                     = "monospace"

[server]
headless = true

[browser]
gatherUsageStats = false
